      DATA (IDUP(I,1),I=1,5)/1,-3,25,2,-4/
      DATA (MOTHUP(1,I,  1),I=1, 5)/  0,  0,  1,  1,  1/
      DATA (MOTHUP(2,I,  1),I=1, 5)/  0,  0,  2,  2,  2/
      DATA (ICOLUP(1,I,  1),I=1, 5)/502,  0,  0,502,  0/
      DATA (ICOLUP(2,I,  1),I=1, 5)/  0,501,  0,  0,501/
      DATA (IDUP(I,2),I=1,5)/3,-1,25,4,-2/
      DATA (MOTHUP(1,I,  2),I=1, 5)/  0,  0,  1,  1,  1/
      DATA (MOTHUP(2,I,  2),I=1, 5)/  0,  0,  2,  2,  2/
