ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'R2_UUZ_V2 = ', R2_UUZ_V2
      WRITE(*,2) 'R2_UUZ_V5 = ', R2_UUZ_V5
      WRITE(*,2) 'R2_sxcW = ', R2_SXCW
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_31 = ', GC_31
      WRITE(*,2) 'GC_32 = ', GC_32
      WRITE(*,2) 'GC_47 = ', GC_47
